language: r

apt_packages:
  - gdal-bin
  - libgdal-dev
  - libgdal1-dev
  - libgdal1h
  - libhdf5-7
  - libhdf5-dev
  - libhdf5-serial-dev
  - libproj-dev
  - netcdf-bin

r_binary_packages:
  - rgdal
  - ggplot2
  - maps
  - RColorBrewer
  
r_github_packages:  
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: F3ywEGAskqvJ6BlCXZgGPjUZkeSN+KRFbHpgKvVaMcf1nSMDfMSDS7X4rgGLLzHMu5lPbu/G69Hw7ousXFiO+b0cWShQcAK6xDYBGXs2MqmQLws3iFFnUKMjHQVwBpTcMPitsqU8gR27xWnC+Du5jzJ7amAO54LxfK3BPHm7cDg=
